### ISSUE TITLE
Are these two images correctly rendered & is it possible to get real world image samples?

### ISSUE THREAD

**Issue by xiaodongww** [allenai/robothor-challenge#20]
Hi, I am wondering if these two images from `RoboTHOR` simulation environment are correctly rendered. The second image is rendered by rotating the camera 30 degrees.  I think the shape of the table is a little weird and the table gets closer to the camera.  Is it supposed to be so? Here are the codes to reproduce the images:
```python
import ai2thor.controller
from PIL import Image

controller = ai2thor.controller.Controller(
    start_unity=True,
    width=640,
    height=480,
    scene='FloorPlan_Train1_1')

event = controller.step(
    dict(action="Teleport", x=8.511058, y=0.9009997, z=-1.57475924)
)
event = controller.step(dict(action="Rotate", rotation=270))
img1 = Image.fromarray(event.frame)
img1.show()

event = controller.step(dict(action="Rotate", rotation=300))
img2 = Image.fromarray(event.frame)
img2.show()
```

<img width="1063" alt="43837A67514DD610880D95A0D9FDF8BB" src="https://user-images.githubusercontent.com/33693065/78572478-1866c700-785a-11ea-9e96-84db2f730617.png">

Do I set the params of `ai2thor.controller.Controller` correctly?  

(BTW: is it possible to release some image samples of the  real environment taken by the LocoBot?)

Any help is appreciated! Thanks in advance.

**Comment by winthos** [comment]
Hello!

It seems the image you are seeing is due to the Agent being in the default mode. The default mode is the "tall" mode of the agent, with a camera FOV of 90 and a higher camera height. This is causing what you are observing in the images, the field of view is "stretching" the table.

Please [refer to the RoboTHOR documentation](https://ai2thor.allenai.org/robothor/documentation/#initialization) to initialize the controller with the correct parameters for the "bot" mode of the agent, which has the same properties as a locobot, including a field of view of 60 which does not have as extreme stretching.

Additionally, we are not able to provide image samples of the real environment at this time.

**Comment by roozbehm** [comment]
Due to the COVID-19 situation, all organizers of the challenge are currently working from home. This prevents us from running experiments on the robot and providing you with real images.

**Comment by xiaodongww** [comment]
It really works. Thank you very much!
