### ISSUE TITLE
A problem about the data.

### ISSUE THREAD

**Issue by liuxz-cs** [allenai/robothor-challenge#24]
In the data file train.json and val.json, the "y" value in "shortest_path" seem incorrect compared with the "y" in "initial_position". For example, in "Train_1_1_Apple_0", the "y" in "initial_position" is 0.9009997, but "y" in "shortest_path" is all 0.0103442669, so does the value of "y" have some special meaning? Which action will lead to the that value?

**Comment by AlvaroHG** [comment]
Hi!
Yes you are correct, due to a technicality of how the routes were generated, the `y` coordinate in `shortest_path` are the floor coordinates of the route (where the agent is stepping). So for now you can ignore those `y` values and use the one in `initial_position`. 
We will update the dataset shortly with the correct coordinates.

Thank you!

**Comment by AlvaroHG** [comment]
Dataset updated last week `y` values in the path are consistent with `initial_position.
Thanks!
