### ISSUE TITLE
Top-down Map

### ISSUE THREAD

**Issue by rrwiyatn** [allenai/robothor-challenge#7]
Hi, is there a way to get a top-down map so we can visualize the trajectory of the agent from a bird's eye view in RoboThor? Thanks!

**Comment by mattdeitke** [comment]
Yes. Use
`controller.step(action='ToggleMapView')`

It should be noted that this function is still in production, but has been successfully tested for all RoboTHOR scenes.

Using ToggleMapView is how we captured the footage shown here:
https://www.youtube.com/watch?v=KcELPpdN770&t=115

**Comment by rrwiyatn** [comment]
Hi Matt, thanks for the pointers! The `ToggleMapView` seems to work and behave like you described. I tried running `AddThirdPartyCamera` but it won't finish executing on RoboTHOR scene (my code gets stuck at that line when I called `AddThirdPartyCamera` action). Is this expected?

**Comment by rrwiyatn** [comment]
Hi, any updates regarding this?

Also, is there an easy way to overlay the trajectory of the agent on the top-down image? (so we can visualize the movement of the robot within an episode as a single image rather than a sequence of frames/video/gif)

Thanks!

**Comment by mattdeitke** [comment]
Hey, sorry for the late response.

**AddThirdPartyCamera**. Do you mind attaching the code you used to try and instantiate a third party camera? Not sure why it would be broken off the top of my head.

---

**Single map trajectory view**. Nothing officially supported in terms of documented functions, but internally I've used some computer graphics tricks to easily to this with numpy. Basically, it takes the maximum pixel value across a set of RGB images, which always show the robot over the ground (since the robot is white and the ground is dark). Self contained demo with AI2-THOR below.

With the robothor-challenge agent the only difference is that `c` would be `r.controller`.

![image](https://user-images.githubusercontent.com/28768645/76371280-08a9a080-62f7-11ea-9bbb-21d6de858a2a.png)

Matt.

**Comment by rrwiyatn** [comment]
That's a nice trick. Thanks!

OK, so it turns out that `AddThirdPartyCamera` does not work only when I initialize Controller with `renderObjectImage = True`. Is this expected?

**Comment by mattdeitke** [comment]
Ok, thanks! I was able to reproduce this bug.

At a first glance, I don't know of an immediate fix. Definitely not expected. Will keep you posted if there's updates.

**Comment by rrwiyatn** [comment]
Great, thanks! I will keep this issue open for now, but feel free to close it.
